package com.tc.client.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tc.client.db.DBServer;

import com.tc.client.db.DBServerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBServerDaoConfig;

    private final DBServerDao dBServerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBServerDaoConfig = daoConfigMap.get(DBServerDao.class).clone();
        dBServerDaoConfig.initIdentityScope(type);

        dBServerDao = new DBServerDao(dBServerDaoConfig, this);

        registerDao(DBServer.class, dBServerDao);
    }
    
    public void clear() {
        dBServerDaoConfig.clearIdentityScope();
    }

    public DBServerDao getDBServerDao() {
        return dBServerDao;
    }

}
