package com.tc.client.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBSERVER".
*/
public class DBServerDao extends AbstractDao<DBServer, Long> {

    public static final String TABLENAME = "DBSERVER";

    /**
     * Properties of entity DBServer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ServerId = new Property(1, String.class, "serverId", false, "SERVER_ID");
        public final static Property ServerName = new Property(2, String.class, "serverName", false, "SERVER_NAME");
        public final static Property ServerIp = new Property(3, String.class, "serverIp", false, "SERVER_IP");
        public final static Property ServerVersion = new Property(4, String.class, "serverVersion", false, "SERVER_VERSION");
        public final static Property HttpServerPort = new Property(5, int.class, "httpServerPort", false, "HTTP_SERVER_PORT");
        public final static Property WsServerPort = new Property(6, int.class, "wsServerPort", false, "WS_SERVER_PORT");
        public final static Property UdpCastServerPort = new Property(7, int.class, "udpCastServerPort", false, "UDP_CAST_SERVER_PORT");
        public final static Property CoverUrl = new Property(8, String.class, "coverUrl", false, "COVER_URL");
    }


    public DBServerDao(DaoConfig config) {
        super(config);
    }
    
    public DBServerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBSERVER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"SERVER_ID\" TEXT UNIQUE ," + // 1: serverId
                "\"SERVER_NAME\" TEXT," + // 2: serverName
                "\"SERVER_IP\" TEXT," + // 3: serverIp
                "\"SERVER_VERSION\" TEXT," + // 4: serverVersion
                "\"HTTP_SERVER_PORT\" INTEGER NOT NULL ," + // 5: httpServerPort
                "\"WS_SERVER_PORT\" INTEGER NOT NULL ," + // 6: wsServerPort
                "\"UDP_CAST_SERVER_PORT\" INTEGER NOT NULL ," + // 7: udpCastServerPort
                "\"COVER_URL\" TEXT);"); // 8: coverUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBSERVER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBServer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String serverId = entity.getServerId();
        if (serverId != null) {
            stmt.bindString(2, serverId);
        }
 
        String serverName = entity.getServerName();
        if (serverName != null) {
            stmt.bindString(3, serverName);
        }
 
        String serverIp = entity.getServerIp();
        if (serverIp != null) {
            stmt.bindString(4, serverIp);
        }
 
        String serverVersion = entity.getServerVersion();
        if (serverVersion != null) {
            stmt.bindString(5, serverVersion);
        }
        stmt.bindLong(6, entity.getHttpServerPort());
        stmt.bindLong(7, entity.getWsServerPort());
        stmt.bindLong(8, entity.getUdpCastServerPort());
 
        String coverUrl = entity.getCoverUrl();
        if (coverUrl != null) {
            stmt.bindString(9, coverUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBServer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String serverId = entity.getServerId();
        if (serverId != null) {
            stmt.bindString(2, serverId);
        }
 
        String serverName = entity.getServerName();
        if (serverName != null) {
            stmt.bindString(3, serverName);
        }
 
        String serverIp = entity.getServerIp();
        if (serverIp != null) {
            stmt.bindString(4, serverIp);
        }
 
        String serverVersion = entity.getServerVersion();
        if (serverVersion != null) {
            stmt.bindString(5, serverVersion);
        }
        stmt.bindLong(6, entity.getHttpServerPort());
        stmt.bindLong(7, entity.getWsServerPort());
        stmt.bindLong(8, entity.getUdpCastServerPort());
 
        String coverUrl = entity.getCoverUrl();
        if (coverUrl != null) {
            stmt.bindString(9, coverUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public DBServer readEntity(Cursor cursor, int offset) {
        DBServer entity = new DBServer( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // serverId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // serverName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // serverIp
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // serverVersion
            cursor.getInt(offset + 5), // httpServerPort
            cursor.getInt(offset + 6), // wsServerPort
            cursor.getInt(offset + 7), // udpCastServerPort
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // coverUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBServer entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setServerName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setServerIp(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setServerVersion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHttpServerPort(cursor.getInt(offset + 5));
        entity.setWsServerPort(cursor.getInt(offset + 6));
        entity.setUdpCastServerPort(cursor.getInt(offset + 7));
        entity.setCoverUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBServer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBServer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBServer entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
